botAccessToken = #botAccessToken Here
maxBumpsPerStream = ####
maxPlayedBumpsPerStream = ###
maxStoredBumps = ###
maxStoredPrio = ###
maxSongsInQ = #max number of songs a user can have in the queue
spreadsheetName = #name of Spreadsheet
songBank = #name of song bank sheet
songHistory = #Name of song history sheet
channel = #Twitch channel
length = ####
views =###
extendedLength = #0
queueLink = #link